// Generated by CoffeeScript 1.5.0
(function() {
  var Entity, Hw,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = require('../Entity').Entity;

  Hw = (function(_super) {

    __extends(Hw, _super);

    function Hw() {
      this.getRacksByZone = __bind(this.getRacksByZone, this);
      Hw.__super__.constructor.apply(this, arguments);
    }

    Hw.prototype.getRacksByZone = function(zone, fn) {
      return this.call("hw/getRacksByZone/" + zone, fn);
    };

    return Hw;

  })(Entity);

  module.exports = Hw;

}).call(this);
