// Generated by CoffeeScript 1.4.0
(function() {
  var Entity, Loc,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = require('../Entity').Entity;

  Loc = (function(_super) {

    __extends(Loc, _super);

    function Loc() {
      this.getAllDatacenters = __bind(this.getAllDatacenters, this);

      this.getAllZones = __bind(this.getAllZones, this);

      this.getAllRooms = __bind(this.getAllRooms, this);
      return Loc.__super__.constructor.apply(this, arguments);
    }

    Loc.prototype.getAllRooms = function(fn) {
      return this.call('loc/getAllRooms', fn);
    };

    Loc.prototype.getAllZones = function(fn) {
      return this.call('loc/getAllZones', fn);
    };

    Loc.prototype.getAllDatacenters = function(fn) {
      var _this = this;
      return this.call('loc/getAllDatacenters', function(err, data) {
        if (err) {
          return fn(err, data);
        }
        return fn(false, data._data);
      });
    };

    return Loc;

  })(Entity);

  module.exports = Loc;

}).call(this);
