// Generated by CoffeeScript 1.6.3
(function() {
  var Entity, Network, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = require('../Entity').Entity;

  Network = (function(_super) {
    __extends(Network, _super);

    function Network() {
      this.ddosList = __bind(this.ddosList, this);
      _ref = Network.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Network.prototype.ddosList = function(fn) {
      return this.call('network/ddos', fn);
    };

    return Network;

  })(Entity);

  module.exports = Network;

}).call(this);
