// Generated by CoffeeScript 1.6.3
(function() {
  var Entity, Loc, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = require('../Entity').Entity;

  Loc = (function(_super) {
    __extends(Loc, _super);

    function Loc() {
      this.getServerInfo = __bind(this.getServerInfo, this);
      this.getAllServers = __bind(this.getAllServers, this);
      _ref = Loc.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Loc.prototype.getAllServers = function(fn) {
      return this.call('server', fn);
    };

    Loc.prototype.getServerInfo = function(server_id, fn) {
      return this.call("server/" + server_id, fn);
    };

    return Loc;

  })(Entity);

  module.exports = Loc;

}).call(this);
