// Generated by CoffeeScript 1.6.3
(function() {
  var Entity, User, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Entity = require('../Entity').Entity;

  User = (function(_super) {
    __extends(User, _super);

    function User() {
      this.getUser = __bind(this.getUser, this);
      _ref = User.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    User.prototype.getUser = function(fn) {
      return this.call('user', fn);
    };

    return User;

  })(Entity);

  module.exports = User;

}).call(this);
