// Generated by CoffeeScript 1.4.0
(function() {
  var BaseBot,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  BaseBot = (function() {

    function BaseBot(options) {
      this.options = options;
      this.getjQuery = __bind(this.getjQuery, this);

      this.visit = __bind(this.visit, this);

      this.init = __bind(this.init, this);

      this.handleOptions = __bind(this.handleOptions, this);

      this.debug = __bind(this.debug, this);

      this.log = __bind(this.log, this);

      this.handleOptions();
      this.init();
      this.debug("Bot is ready");
    }

    BaseBot.prototype.log = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return console.log.apply(console, ["OnlineBot>"].concat(__slice.call(args)));
    };

    BaseBot.prototype.debug = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (this.options.verbose !== false) {
        return this.log.apply(this, args);
      }
    };

    BaseBot.prototype.handleOptions = function() {
      var _base, _ref;
      if ((_ref = (_base = this.options).verbose) == null) {
        _base.verbose = false;
      }
      return this.debug("handleOptions()");
    };

    BaseBot.prototype.init = function() {
      this.browser = new (require('zombie'));
      return this.debug("init()");
    };

    BaseBot.prototype.visit = function(path, fn) {
      var _this = this;
      if (fn == null) {
        fn = null;
      }
      this.debug("Visiting " + path);
      return this.browser.visit("" + this.options.base_url + path, function() {
        _this.debug("" + path + " is loaded");
        if (fn) {
          return fn();
        }
      });
    };

    BaseBot.prototype.getjQuery = function() {
      return this.browser.window.jQuery;
    };

    return BaseBot;

  })();

  module.exports = BaseBot;

}).call(this);
