// Generated by CoffeeScript 1.6.3
(function() {
  var ApiV1, api, apiKey,
    _this = this;

  ApiV1 = require('..').ApiV1;

  apiKey = require('./credentials').apiKey;

  api = new ApiV1({
    apiKey: apiKey
  });

  api.user.getUser(function(err, user) {
    if (err) {
      return console.error(err);
    }
    return console.log(user);
  });

}).call(this);
