// Generated by CoffeeScript 1.4.0
(function() {
  var OnlineBot, bot, credentials;

  OnlineBot = require('..').OnlineBot;

  credentials = require('./credentials');

  bot = new OnlineBot({
    username: credentials.username,
    password: credentials.password,
    verbose: true
  });

  bot.auth(function() {
    console.log("Connected");
    return bot.servers(function(servers) {
      var server, _i, _len, _results;
      console.log("Servers: ");
      _results = [];
      for (_i = 0, _len = servers.length; _i < _len; _i++) {
        server = servers[_i];
        _results.push(bot.getServerStats(server.id, function(stats) {
          var graph, graphs, kind, period, _results1;
          _results1 = [];
          for (kind in stats) {
            graphs = stats[kind];
            console.log("=== " + kind + " ===");
            _results1.push((function() {
              var _results2;
              _results2 = [];
              for (period in graphs) {
                graph = graphs[period];
                _results2.push(console.log("" + period + ": " + graph));
              }
              return _results2;
            })());
          }
          return _results1;
        }));
      }
      return _results;
    });
  });

}).call(this);
