// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports.Entity = (function() {

    function Entity(api) {
      this.api = api;
      this.call = __bind(this.call, this);

    }

    Entity.prototype.call = function(path, fn) {
      return this.api.call(path, fn);
    };

    return Entity;

  })();

}).call(this);
